# Generated by Django 4.2 on 2025-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_info', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
            ],
        ),
    ]
